/*
Package v1 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

This package was generated by /home/benm/go/src/github.com/benmaddison/topographly/vendor/github.com/openconfig/ygot/ygen/commongen.go
using the following YANG input files:
	- yang/topology-v1.yang
Imported modules were sourced from:
	- yang/...
*/
package v1

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Root{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Root represents the /root YANG schema element.
type Root struct {
	Topology	*Topology	`path:"topology" module:"topographly-v1"`
}

// IsYANGGoStruct ensures that Root implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Root) IsYANGGoStruct() {}

// GetOrCreateTopology retrieves the value of the Topology field
// or returns the existing field if it already exists.
func (t *Root) GetOrCreateTopology() *Topology {
	if t.Topology != nil {
		return t.Topology
	}
	t.Topology = &Topology{}
	return t.Topology
}

// GetTopology returns the value of the Topology struct pointer
// from Root. If the receiver or the field Topology is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Root) GetTopology() *Topology {
	if t != nil && t.Topology != nil {
		return t.Topology
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Root) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Root"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Root) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Topology represents the /topographly-v1/topology YANG schema element.
type Topology struct {
	Link	map[string]*Topology_Link	`path:"links/link" module:"topographly-v1"`
	Node	map[string]*Topology_Node	`path:"nodes/node" module:"topographly-v1"`
}

// IsYANGGoStruct ensures that Topology implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Topology) IsYANGGoStruct() {}

// NewLink creates a new entry in the Link list of the
// Topology struct. The keys of the list are populated from the input
// arguments.
func (t *Topology) NewLink(IpPrefix string) (*Topology_Link, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Link == nil {
		t.Link = make(map[string]*Topology_Link)
	}

	key := IpPrefix

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Link[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Link", key)
	}

	t.Link[key] = &Topology_Link{
		IpPrefix: &IpPrefix,
	}

	return t.Link[key], nil
}

// GetOrCreateLink retrieves the value with the specified keys from
// the receiver Topology. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Topology) GetOrCreateLink(IpPrefix string) (*Topology_Link){

	key := IpPrefix

	if v, ok := t.Link[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewLink(IpPrefix)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateLink got unexpected error: %v", err))
	}
	return v
}

// GetLink retrieves the value with the specified key from
// the Link map field of Topology. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Topology) GetLink(IpPrefix string) (*Topology_Link){

	if t == nil {
		return nil
	}

  key := IpPrefix

  if lm, ok := t.Link[key]; ok {
    return lm
  }
  return nil
}

// DeleteLink deletes the value with the specified keys from
// the receiver Topology. If there is no such element, the function
// is a no-op.
func (t *Topology) DeleteLink(IpPrefix string) {
	key := IpPrefix

	delete(t.Link, key)
}

// NewNode creates a new entry in the Node list of the
// Topology struct. The keys of the list are populated from the input
// arguments.
func (t *Topology) NewNode(Hostname string) (*Topology_Node, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Node == nil {
		t.Node = make(map[string]*Topology_Node)
	}

	key := Hostname

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Node[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Node", key)
	}

	t.Node[key] = &Topology_Node{
		Hostname: &Hostname,
	}

	return t.Node[key], nil
}

// GetOrCreateNode retrieves the value with the specified keys from
// the receiver Topology. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Topology) GetOrCreateNode(Hostname string) (*Topology_Node){

	key := Hostname

	if v, ok := t.Node[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewNode(Hostname)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateNode got unexpected error: %v", err))
	}
	return v
}

// GetNode retrieves the value with the specified key from
// the Node map field of Topology. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Topology) GetNode(Hostname string) (*Topology_Node){

	if t == nil {
		return nil
	}

  key := Hostname

  if lm, ok := t.Node[key]; ok {
    return lm
  }
  return nil
}

// DeleteNode deletes the value with the specified keys from
// the receiver Topology. If there is no such element, the function
// is a no-op.
func (t *Topology) DeleteNode(Hostname string) {
	key := Hostname

	delete(t.Node, key)
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Topology) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Topology"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Topology) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Topology_Link represents the /topographly-v1/topology/links/link YANG schema element.
type Topology_Link struct {
	EndpointA	*string	`path:"config/endpoint-a" module:"topographly-v1"`
	EndpointZ	*string	`path:"config/endpoint-z" module:"topographly-v1"`
	IpPrefix	*string	`path:"config/ip-prefix|ip-prefix" module:"topographly-v1"`
}

// IsYANGGoStruct ensures that Topology_Link implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Topology_Link) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Topology_Link struct, which is a YANG list entry.
func (t *Topology_Link) ΛListKeyMap() (map[string]interface{}, error) {
	if t.IpPrefix == nil {
		return nil, fmt.Errorf("nil value for key IpPrefix")
	}

	return map[string]interface{}{
		"ip-prefix": *t.IpPrefix,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Topology_Link) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Topology_Link"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Topology_Link) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Topology_Node represents the /topographly-v1/topology/nodes/node YANG schema element.
type Topology_Node struct {
	Hostname	*string	`path:"config/hostname|hostname" module:"topographly-v1"`
}

// IsYANGGoStruct ensures that Topology_Node implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Topology_Node) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Topology_Node struct, which is a YANG list entry.
func (t *Topology_Node) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Hostname == nil {
		return nil, fmt.Errorf("nil value for key Hostname")
	}

	return map[string]interface{}{
		"hostname": *t.Hostname,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Topology_Node) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Topology_Node"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Topology_Node) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }



var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5c, 0xcd, 0x6e, 0xdb, 0x30,
		0x0c, 0xbe, 0xe7, 0x29, 0x0c, 0x9d, 0x9b, 0xba, 0xdd, 0x65, 0x83, 0x6f, 0x5d, 0xb7, 0x61, 0x40,
		0x7f, 0x56, 0xac, 0xbd, 0x0f, 0x46, 0xa2, 0x24, 0x42, 0x1d, 0xc9, 0x90, 0x94, 0xae, 0xe9, 0xd0,
		0x77, 0x1f, 0x6c, 0xd9, 0x8e, 0xed, 0x38, 0xb1, 0x28, 0xb9, 0xdd, 0x12, 0x10, 0x28, 0x82, 0x46,
		0xd6, 0x0f, 0x45, 0x7e, 0xfa, 0x4c, 0x52, 0x44, 0xfe, 0x8c, 0x82, 0x20, 0x08, 0xc8, 0x6d, 0xbc,
		0xa4, 0x24, 0x0a, 0x88, 0x14, 0x42, 0x93, 0x13, 0xd3, 0x76, 0xc5, 0xf8, 0x94, 0x44, 0xc1, 0x79,
		0xf1, 0xf5, 0x52, 0xf0, 0x19, 0x9b, 0x93, 0x28, 0x38, 0x2b, 0x1a, 0xbe, 0x30, 0x49, 0xa2, 0xc0,
		0x4c, 0x90, 0x37, 0x68, 0x91, 0x8a, 0x44, 0xcc, 0xd7, 0x8d, 0xd6, 0xc6, 0xf4, 0x55, 0x8f, 0x93,
		0xe6, 0xf3, 0xe6, 0x52, 0x55, 0x73, 0x7b, 0xc9, 0xea, 0xc1, 0x9d, 0xa4, 0x33, 0xf6, 0xbc, 0xb5,
		0x4e, 0x73, 0xad, 0xf9, 0xf8, 0xe9, 0xbc, 0xb5, 0x50, 0xde, 0xe1, 0x5e, 0xac, 0xe4, 0x84, 0x76,
		0x0e, 0x36, 0xc2, 0xd0, 0xf5, 0x6f, 0x21, 0x33, 0x79, 0x48, 0x6a, 0xd6, 0x39, 0xe9, 0xee, 0xf8,
		0x3d, 0x56, 0x17, 0x72, 0xbe, 0x5a, 0x52, 0xae, 0x49, 0x14, 0x68, 0xb9, 0xa2, 0x3b, 0x3a, 0xd6,
		0x7a, 0x15, 0x62, 0x6d, 0xf5, 0x7b, 0x6d, 0xb4, 0xbc, 0xb6, 0xf6, 0xdb, 0x56, 0x75, 0xf5, 0x20,
		0x61, 0xfc, 0x51, 0xed, 0xde, 0x4a, 0xa9, 0x0b, 0xd3, 0x6d, 0x87, 0x74, 0xdd, 0xca, 0xef, 0x35,
		0x82, 0x8d, 0x31, 0xac, 0x8d, 0x62, 0x6b, 0x1c, 0xb0, 0x91, 0xc0, 0xc6, 0x82, 0x18, 0xad, 0xdb,
		0x78, 0x3b, 0x8c, 0xd8, 0x6b, 0xcc, 0x86, 0x51, 0xfb, 0x35, 0x50, 0xb7, 0x6d, 0xdf, 0xe6, 0xf7,
		0x9b, 0xd8, 0xda, 0xd4, 0x10, 0x93, 0x83, 0x4d, 0x0f, 0x85, 0x80, 0x33, 0x14, 0x9c, 0x21, 0xe1,
		0x02, 0x8d, 0xfd, 0x10, 0xe9, 0x81, 0x8a, 0x35, 0x64, 0xaa, 0x8e, 0x93, 0xd2, 0x82, 0x96, 0xba,
		0x2b, 0x8d, 0x53, 0x8c, 0xb3, 0xdc, 0xbf, 0x1d, 0x9c, 0xc0, 0xb0, 0x72, 0x81, 0x97, 0x33, 0xcc,
		0x5c, 0xe1, 0xe6, 0x0d, 0x3b, 0x6f, 0xf8, 0xf9, 0xc0, 0xd0, 0x0e, 0x8e, 0x96, 0xb0, 0x04, 0xc3,
		0xb3, 0x1a, 0x40, 0xf9, 0x34, 0x15, 0x8c, 0xeb, 0x71, 0x0c, 0xd7, 0x7b, 0x69, 0xe8, 0xda, 0x1c,
		0x40, 0xbd, 0x15, 0xf0, 0x3d, 0x03, 0x0e, 0x83, 0xc2, 0xd8, 0x07, 0xce, 0xde, 0xb0, 0xf6, 0x85,
		0xf7, 0x60, 0x30, 0x1f, 0x0c, 0xee, 0x43, 0xc0, 0x1e, 0x06, 0x7f, 0xe0, 0x31, 0xa8, 0x04, 0x7c,
		0x58, 0xa7, 0xd4, 0xcf, 0xda, 0x5c, 0x4c, 0xe9, 0x58, 0xd2, 0x99, 0x8b, 0xc1, 0x4b, 0x72, 0xfe,
		0xe8, 0x30, 0xf6, 0x2e, 0xd6, 0x8b, 0x6c, 0xfd, 0xd3, 0xd3, 0xb0, 0xfa, 0xcb, 0x64, 0x51, 0xf9,
		0x67, 0xb8, 0x10, 0x4a, 0xf3, 0x4c, 0xc4, 0xd1, 0xdb, 0x28, 0x1b, 0xa0, 0xe8, 0xcd, 0xf1, 0x7f,
		0x19, 0x80, 0x42, 0x5e, 0x90, 0x42, 0x90, 0x42, 0x8e, 0x8b, 0x42, 0x12, 0x1a, 0xcf, 0x90, 0x41,
		0xf6, 0x89, 0xca, 0xd2, 0x71, 0xea, 0x76, 0xac, 0x2a, 0x25, 0x6f, 0xa6, 0x40, 0xfe, 0x40, 0xfe,
		0x38, 0x2a, 0xfe, 0x50, 0x5a, 0x32, 0x3e, 0xf7, 0xa1, 0x8f, 0x4f, 0x6f, 0x75, 0xc6, 0x07, 0x8d,
		0x5d, 0x2e, 0x38, 0x17, 0x3a, 0xd6, 0x4c, 0x70, 0x58, 0x08, 0xa3, 0x26, 0x0b, 0xba, 0x8c, 0xd3,
		0x82, 0xee, 0x42, 0x2d, 0x52, 0x31, 0x97, 0x71, 0xba, 0x48, 0xd6, 0xe3, 0xa7, 0xf3, 0xb0, 0x4c,
		0x74, 0x86, 0x79, 0xe6, 0x2d, 0xff, 0x0c, 0x8b, 0x18, 0x7b, 0x34, 0xcc, 0x1e, 0x2d, 0xf6, 0xe7,
		0xc0, 0x70, 0xce, 0xcc, 0x06, 0x64, 0x34, 0xcc, 0x09, 0x1c, 0x7b, 0x4e, 0x00, 0xcc, 0x40, 0x1e,
		0x9e, 0x8b, 0x8b, 0xc7, 0x52, 0xf7, 0x54, 0xcc, 0xc9, 0x0c, 0x37, 0x98, 0x7f, 0xc7, 0x33, 0xaa,
		0x74, 0xac, 0x29, 0xfc, 0x7c, 0x9a, 0x61, 0x6f, 0x9c, 0xaf, 0xfb, 0x80, 0x67, 0x13, 0xf3, 0x75,
		0x98, 0xaf, 0x43, 0x67, 0x19, 0x9d, 0x65, 0xcc, 0xd7, 0x61, 0xbe, 0x0e, 0x29, 0x04, 0x29, 0x04,
		0xf3, 0x75, 0x98, 0xaf, 0x43, 0xfe, 0x40, 0xfe, 0xc0, 0x7c, 0xdd, 0xd1, 0xe7, 0xeb, 0x4c, 0x88,
		0x3d, 0x54, 0x2a, 0xc0, 0xab, 0xfe, 0xe7, 0x8a, 0xae, 0x21, 0xf4, 0x45, 0xae, 0x99, 0xd2, 0x17,
		0x5a, 0x5b, 0x16, 0x0d, 0xdd, 0x30, 0xfe, 0x35, 0xa1, 0xd9, 0xf9, 0x50, 0x24, 0x0a, 0xf8, 0x2a,
		0x49, 0x2c, 0xf2, 0x16, 0x37, 0xf1, 0x33, 0x7c, 0xd0, 0x0f, 0x39, 0xa5, 0x92, 0x4e, 0x3f, 0xaf,
		0x8b, 0x21, 0x5e, 0x4a, 0x01, 0x22, 0x01, 0x8e, 0x00, 0x62, 0x95, 0xbe, 0x91, 0xab, 0x89, 0x79,
		0x45, 0x46, 0x01, 0x79, 0x28, 0x26, 0xf9, 0x75, 0x9d, 0x0d, 0x1f, 0xb9, 0x01, 0x02, 0x56, 0x4d,
		0x68, 0xa9, 0x05, 0xd0, 0xee, 0xbb, 0x25, 0xdf, 0x96, 0xab, 0x43, 0xa6, 0x3c, 0x14, 0xb2, 0xa8,
		0x48, 0x35, 0xdd, 0xb0, 0x22, 0xf5, 0x30, 0x2a, 0x52, 0x33, 0x6b, 0xd9, 0x57, 0xa4, 0xe6, 0xbd,
		0xb1, 0x22, 0x15, 0x2b, 0x52, 0xb1, 0x22, 0x15, 0x33, 0xdc, 0x07, 0x92, 0xe1, 0xae, 0x02, 0x5d,
		0xe7, 0xd8, 0xb2, 0x9a, 0x01, 0x43, 0x4b, 0x0c, 0x2d, 0x31, 0xb4, 0xc4, 0xd0, 0xb2, 0xed, 0x5a,
		0xd7, 0xd2, 0x6a, 0xef, 0x5f, 0x0a, 0x02, 0xe6, 0x37, 0x57, 0x5e, 0xc3, 0x42, 0x10, 0x7c, 0x15,
		0xfb, 0xf1, 0xcf, 0xbf, 0x2f, 0x04, 0x81, 0x65, 0xbd, 0xb1, 0x0e, 0x04, 0x8f, 0x26, 0x7a, 0xc9,
		0xe8, 0x25, 0xa3, 0x97, 0x8c, 0x5e, 0x32, 0x7a, 0xc9, 0x03, 0x7a, 0xc9, 0xff, 0xdf, 0x05, 0x8c,
		0x25, 0x7b, 0xe1, 0xfd, 0xcb, 0x20, 0x00, 0xf0, 0xb8, 0x7f, 0xb9, 0xcd, 0x86, 0x1f, 0xe2, 0xfd,
		0x8b, 0xb9, 0x17, 0xb1, 0xbd, 0x7f, 0xd9, 0xfb, 0xa3, 0x21, 0x3d, 0x92, 0x59, 0x4a, 0xd4, 0xf5,
		0x0b, 0x2a, 0xdd, 0x4a, 0x6f, 0x4a, 0xbd, 0x91, 0xcd, 0xfc, 0x57, 0x48, 0xb7, 0x4b, 0x2a, 0xc2,
		0xd4, 0xa5, 0x58, 0xa6, 0x92, 0x2a, 0x45, 0xa7, 0xf7, 0xb9, 0x64, 0x5b, 0x6f, 0x1c, 0xc2, 0xd4,
		0xb7, 0xf8, 0x91, 0xfe, 0x14, 0x62, 0xfb, 0x6d, 0xd4, 0xde, 0x0d, 0xa9, 0x3f, 0x6a, 0x88, 0x9b,
		0x0f, 0x37, 0x22, 0x8d, 0x5e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
		0x1f, 0x78, 0x89, 0xf4, 0xff, 0x46, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
}

